INSTRUCTIONS_PAGE_0 = 0
INSTRUCTIONS_PAGE_1 = 1
GAME_RUNNING = 2
GAME_OVER = 3

OBJECT_SPRITE_SCALING = 0.5

PLAYER_SPRITE_SCALING = 0.5
PLAYER_SPRITE_SIZE = 32 * PLAYER_SPRITE_SCALING

CREATURE_SPRITE_SCALING = PLAYER_SPRITE_SCALING

WALL_SPRITE_SCALING = 1
WALL_SPRITE_SIZE = 32 * WALL_SPRITE_SCALING

# How big the grid is
GRID_WIDTH = 35
GRID_HEIGHT = 35

AREA_WIDTH = int(GRID_WIDTH * WALL_SPRITE_SIZE)
AREA_HEIGHT = int(GRID_HEIGHT * WALL_SPRITE_SIZE)

# How fast the player moves
MOVEMENT_SPEED = 5
FIREBALL_SPEED = 7

# How close the player can get to the edge before we scroll.
VIEWPORT_MARGIN = 300

# How big the window is
WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800

MERGE_SPRITES = True

